Solution 1

I library is a bundle of code which provides multiple funtions that can be simply imported without having to write it from scratch.

It simplifies our code. Enhances reusability.

Solution 2

Array : They are fast. They are immutable. Homogenous
    
list : They are comparatively slow. They are mutable. Heterogenous.

Solution 3

In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

print(arr.ndim)

2


Solution 4

In [8]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

arr[0]


array([1, 2, 3, 4])

Solution 5

In [9]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

arr[2][3]

12

Solution 6

In [17]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if i%2!=0 and j%2!=0:
            print(arr[i][j])

6
8


Solution 7

In [19]:
arr = np.random.randint(0,2,(3,3))
arr

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 1]])

Solution 8


arr = np.random.rand - Gives us an array of random numbers of the given size

arr = np.random.randn - Gives us an array of random number of a given size which are normally distributed.

Soluiton 9

In [22]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

arr = np.expand_dims(arr, axis=0)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

Solution 10

In [23]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Solution 11

In [25]:
a = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
b = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

In [26]:
#1

a * b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

#2 

Not possible since Number of columns in first matrix is not equal to 2nd matrix

In [29]:
#3

a+b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [30]:
#4

a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
#5

a/b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Solution 12

np.ndarray.byteswap()

Solution 13

np.linalg.inv() is used to compute the inverse of a matrix.

Solution 14

np.reshape() - It changes the shape of the array without altering its data.

In [33]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Solution 15

Broadcasting refers to the automatic expansion of smaller arrays to match the shape of larger arrays during arithmetic operations.

In [35]:
arr = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

a = np.array([1,2,3,4])


arr+a

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])